spam_championship/urls.py
# coding: utf-8

"""spam_championship URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from spc import views as spc_views
from allauth.socialaccount.providers.oauth.urls import default_urlpatterns

from spc.provider import ManiaplanetOAuth2Provider


urlpatterns = [
    default_urlpatterns(ManiaplanetOAuth2Provider)[0],
    url(r'^admin/', admin.site.urls),
    url(r'^$', spc_views.home),
    url(r'^editions/', spc_views.editions),
    url(r'^edition/(?P<pk>\d+)$', spc_views.LireEdition.as_view()),
    url(r'^rules/', spc_views.rules),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^login/$', spc_views.user_login, name='login'),
    url(r'^subscribe/$', spc_views.subscribe, name='subscribe'),
    url(r'^unsubscribe/$', spc_views.unsubscribe, name='unsubscribe'),
    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^register/$', spc_views.register, name='register'),
    url(r'^edit/$', spc_views.edit, name='edit'),

    # login / logout urls
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^logout-then-login/$', auth_views.logout_then_login, name='logout_then_login'),
    url(r'^logged_out/', spc_views.logged_out, name='logged_out'),


    # change password urls
    url(r'^password-change/$', auth_views.password_change, name='password_change'),
    url(r'^password-change/done/$', auth_views.password_change_done, name='password_change_done'),

    # restore password urls
    url(r'^password-reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password-reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^password-reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^accounts/', include('allauth.urls')),
]

spc/models.py
# coding: utf-8

from __future__ import unicode_literals
from datetime import datetime, timedelta
from django.contrib import admin
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.conf import settings
from tinymce.models import HTMLField
import mysql.connector
from django.core.exceptions import ObjectDoesNotExist


def get_now():
    return datetime.now()


class User(AbstractUser):
    nickname = models.TextField(max_length=500)


class Classement(models.Model):
    last_updated_date = models.DateTimeField(null=True)


class LigneClassement(models.Model):
    # TODO: remove null option
    player_id = models.ForeignKey(User, null=True)
    position = models.IntegerField()

class New(models.Model):

    author_id = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=128, unique=True)
    content = HTMLField()
    content_en = HTMLField()
    active = models.BooleanField(default=False)
    create_date = models.DateTimeField(default=get_now, editable=False)


class Edition(models.Model):

    date_start = models.DateTimeField()
    date_end = models.DateTimeField()
    numero = models.CharField(max_length=4, unique=True)
    joueur_ids = models.ManyToManyField(settings.AUTH_USER_MODEL)
    subscribe_date_start = models.DateTimeField()
    subscribe_date_end = models.DateTimeField()


class EditionQualif(models.Model):

    edition_id = models.OneToOneField(Edition, unique=True)
    date_start = models.DateTimeField()
    date_end = models.DateTimeField()

    def save(self, *args, **kwargs):
        is_new = True if not self.id else False
        super(EditionQualif, self).save(*args, **kwargs)
        if is_new:
            cq = ClassementQualif(qualif_id=self)
            cq.save()

    def get_classement_qualif(self):
        """
        récupère les données depuis la base de données distante ou depuis la base de données locale
        (pour ne pas trop faire d'appels)
        retourne une liste de dictionnaires ayant pour clés : position, login, pseudo et user_id
        """
        try:
            classement = self.classementqualif
        except ObjectDoesNotExist:
            return False
        last_updated_date = classement.last_updated_date
        cpt = 1
        # si la dernière mise à jour date de moins de 5 minutes alors on affiche le classement stocké
        if last_updated_date and last_updated_date > datetime.now()-timedelta(seconds=300):
            return self.classementqualif
        try:
            conn = mysql.connector.connect(host='localhost', user='root', database='Spam_Tech', password='cocorico')
        except Exception as ex:
            return False
        try:
            cursor = conn.cursor()
            cursor.execute(
                "select players.login, players.nickname, rs_rank.playerid from players inner join rs_rank on (players.id = rs_rank.playerid);"
            )
            rows = cursor.fetchall()
            for row in rows:
                try:
                    user = User.objects.get(username=row[0])
                except User.DoesNotExist:
                    user = None
                ligne = LigneClassementQualif(player_id=user, position=cpt, classement_qualif_id=classement)
                ligne.save()
                cpt += 1
        except Exception as exc:
            return False
        finally:
            conn.close()
        classement.last_updated_date = datetime.now()
        classement.save()
        self.classementqualif = classement
        self.save()
        return classement


class EditionDemi(models.Model):

    edition_id = models.ForeignKey(Edition, related_name='demi_ids')
    date_start = models.DateTimeField()
    date_end = models.DateTimeField()
    joueur_ids = models.ManyToManyField(settings.AUTH_USER_MODEL)


class EditionFinale(models.Model):

    edition_id = models.ForeignKey(Edition)
    date_start = models.DateTimeField()
    date_end = models.DateTimeField()
    joueur_ids = models.ManyToManyField(settings.AUTH_USER_MODEL)


class ClassementQualif(Classement):
    qualif_id = models.OneToOneField(EditionQualif, on_delete=models.CASCADE, primary_key=True)


class ClassementDemi(Classement):
    demi_id = models.ForeignKey(EditionDemi, on_delete=models.CASCADE, primary_key=True)


class ClassementFinale(Classement):
    finale_id = models.OneToOneField(EditionFinale, on_delete=models.CASCADE, primary_key=True)


class LigneClassementQualif(LigneClassement):
    classement_qualif_id = models.ForeignKey(ClassementQualif)


class LigneClassementDemi(LigneClassement):
    classement_demi_id = models.ForeignKey(ClassementDemi)


class LigneClassementFinale(LigneClassement):
    classement_finale_id = models.ForeignKey(ClassementFinale)


class Map(models.Model):


    nom = models.CharField(max_length=128, unique=True)
    edition_ids = models.ManyToManyField(
        Edition,
    )


class Rule(models.Model):

    content = HTMLField()
    content_en = HTMLField()
    active = models.BooleanField(default=False)



@admin.register(New)
class NewAdmin(admin.ModelAdmin):

    date_hierarchy = 'create_date'
    list_display = ('title', 'author_id', 'create_date', 'active')
    fields = ('title', 'content', 'content_en', 'active')

    def save_model(self, request, obj, form, change):
        obj.author_id = request.user
        super(NewAdmin, self).save_model(request, obj, form, change)


@admin.register(User)
class UserAdmin(admin.ModelAdmin):

    def save_model(self, request, obj, form, change):
        obj.user = request.user
        super(UserAdmin, self).save_model(request, obj, form, change)


class EditionQualifInline(admin.StackedInline):
    model = EditionQualif


@admin.register(Edition)
class EditionAdmin(admin.ModelAdmin):

    fields = ('numero', 'date_start', 'date_end', 'subscribe_date_start', 'subscribe_date_end')
    list_display = ('numero', 'date_start', 'date_end')
    inlines = [
        EditionQualifInline,
    ]

spc/forms.py
# coding: utf-8

from django import forms
from django.contrib import admin
from spc.models import Rule, New
from tinymce.widgets import TinyMCE


class UnsubscribeForm(forms.Form):
    edition_id = forms.CharField()


class SubscribeForm(forms.Form):
    edition_id = forms.CharField()


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class NewForm(forms.ModelForm):

    content = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
    content_en = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))

    class Meta:
        model = New
        fields = ('content', 'content_en', 'active')


class NewFormAdmin(admin.ModelAdmin):
    model = NewForm
    fields = ('content', 'content_en', 'active')

class RuleForm(forms.ModelForm):

    content = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
    content_en = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))

    class Meta:
        model = Rule
        fields = ('content', 'content_en', 'active')


class RuleFormAdmin(admin.ModelAdmin):
    model = RuleForm
    fields = ('content', 'content_en', 'active')

spc/templates/spc/base.html
{% load i18n %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>Spam Championship</title>
        <link rel="stylesheet" href="http://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" type="text/css" href="{% static "/css/custom.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "/css/bootstrap.min.css" %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <!--<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.9/validator.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $('#select-languages').on('change', function() {
                    $('#form-languages').submit();
                });
            });
        </script>
    </head>
    <body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="http://spamteam.forumactif.org" target="blank"><img class="logo" src="{% static "/img/serpent.png" %}"/></img></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/">{% trans "Accueil" %}<span class="sr-only">(current)</span></a></li>
                    <li><a href="/editions">{% trans "Editions" %}</a></li>
                    <li><a href="/rules">{% trans "Règlement" %}</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <form id="form-languages" action="/i18n/setlang/" method="post">
                            {% csrf_token %}
                            <input name="next" type="hidden" value="{{ request.path }}" />
                            <div style="height: 64px !important;">
                            <select id="select-languages" class="selectpicker" data-width="fit" name="language" style="height: 64px !important;">
                                {% get_available_languages as LANGUAGES %}
                                {% for lang in LANGUAGES %}
                                {% ifequal user_lang lang.0 %}
                                <option value="{{ lang.0 }}" selected>{{ lang.1 }}</option>
                                {% else %}
                                <option value="{{ lang.0 }}">{{ lang.1 }}</option>
                                {% endifequal %}
                                {% endfor %}
                            </select>
                            </div>
                        </form>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <span>{{ user.nickname|safe }}</span>
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            {% if user.is_superuser %}
                            <li><a href="/admin">Administration</a></li>
                            {% endif %}
                            <li><a href="/edit">Mon compte</a></li>
                            <li><a href="/logout">Logout</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li><a href="{% url "login" %}">Login</a></li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

    <div id="main-container" class="container">
        {% block content %}{% endblock %}
    </div>

    <footer class="footer">
        <div class="container center">
            <span>Spam Team - 2017</span>
            <!-- <img class="logo" src="{% static "/img/Banniere_tech_league.png" %}" style="height: 64px !important;"/></img> -->
        </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>
</html>

spc/templates/spc/detail.html
{% extends "spc/base.html" %}
{% load thumbnail %}

{% block title %}{{ user.get_full_name }}{% endblock %}

{% block content %}
    <h1>{{ user.get_full_name }}</h1>
    <div class="profile-info">
    {% thumbnail user.profile.photo "180x180" crop="100%" as im %}
        <img src="{{ im.url }}" class="user-detail">
    {% endthumbnail %}
    </div>
    {% with total_followers=user.followers.count %}
        <span class="count">
            <span class="total">{{ total_followers }}</span>
            follower{{ total_followers|pluralize }}
        </span>
        <a href="#" data-id="{{ user.id }}" data-action="{% if request.user in user.followers.all %}un{% endif %}follow" class="follow button">
            {% if request.user not in user.followers.all %}
                Follow
            {% else %}
                Unfollow
            {% endif %}
        </a>
        <div id="image-list" class="image-container">
            {% include "images/image/list_ajax.html" with images=user.images_created.all %}
        </div>
    {% endwith %}
{% endblock %}

{% block domready %}
    $('a.follow').click(function(e){
        e.preventDefault();
        $.post('{% url "user_follow" %}',
            {
                id: $(this).data('id'),
                action: $(this).data('action')
            },
            function(data){
                if (data['status'] == 'ok')
                {
                    var previous_action = $('a.follow').data('action');

                    // toggle data-action
                    $('a.follow').data('action', previous_action == 'follow' ? 'unfollow' : 'follow');
                    // toggle link text
                    $('a.follow').text(previous_action == 'follow' ? 'Unfollow' : 'Follow');

                    // update total followers
                    var previous_followers = parseInt($('span.count .total').text());
                    $('span.count .total').text(previous_action == 'follow' ? previous_followers + 1 : previous_followers - 1);
                }
        });
    });
{% endblock %}

spc/templates/spc/edit.html
{% extends "spc/base.html" %}

{% block title %}Modifier votre compte{% endblock %}

{% block content %}
    <h1>Modifier votre compte</h1>
    <form action="." method="post" enctype="multipart/form-data">
	<div class="form-group">
            <label for="id_email">Email</label>
            <input type="email" id="id_email" class="form-control" name="email"/>
        </div>
	<div class="form-group">
            <label for="id_login_trackmania">Login Trackmania</label>
            <input type="text" id="id_login_trackmania" class="form-control" name="login_trackmania"/>
        </div>
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Enregistrer</button>
    </form>
{% endblock %}

spc/templates/spc/edition.html
{% extends "spc/base.html" %}
{% block content %}
<h1> Edition {{ edition.numero }} du {{ edition.date_start|date:"l j F Y h:i" }} au {{ edition.date_end|date:"l j F Y h:i" }} </h1>
    <div style="display: flex; width: 100%">
        <div class="box-shadow" style="width: 33%; margin: 5px; float: right; padding: 10px 10px;">
            <h4><u>Participants</u></h4>
            <br/>
            <table class="table table-striped">
                {% for joueur in edition.joueur_ids.all %}
                <tr><td>{{ joueur.username }}</td></tr>
                {% empty %}
                Aucun joueur n'est inscrit
                {% endfor %}
            </table>
            {% if user.is_authenticated and not subscribed %}
            <form action="{% url "subscribe" %}" method="POST">
                {% csrf_token %}
                <input type="hidden" id="id_edition_id" name="edition_id" value="{{ edition.id }}"/>
                <button type="submit" class="btn btn-primary btn-xs btn-success"/>Je m'inscris</button>
            </form>
            {% elif user.is_authenticated and subscribed %}
            <form action="{% url "unsubscribe" %}" method="POST">
                {% csrf_token %}
                <input type="hidden" id="id_edition_id" name="edition_id" value="{{ edition.id }}"/>
                <button type="submit" class="btn btn-primary btn-xs btn-danger"/>Je me désinscris</button>
            </form>
            {% endif %}
        </div>
        <div class="box-shadow" style="width: 33%; margin: 5px; float: right; padding: 10px 10px;">
            <h4>Informations générales</h4>
        </div>
        <div class="box-shadow" style="width: 33%; margin: 5px; float: right; padding: 10px 10px;">
            <h4><u>Maps</u></h4>
            <br/>
            <table class="table table-striped">
            {% for map in edition.map_set.all %}
            <tr><td>{{ map.nom }}</td></tr>
            {% empty %}
            Aucune map
            {% endfor %}
            </table>
        </div>
    </div>
    <div style="display: flex; width: 100%; margin-top: 5px;">
        <div class="box-shadow" style="width: 100%; margin: 5px;">
            <h4>Qualifications</h4>
            <br/>
            {% if erreur %}
            <p>Le classement n'est pas disponible</p>
            {% endif %}
            <table class="table table-striped">
                <tr><th>Position</th><th>Login</th><th>Pseudo</th><th></th>
                {% for line in ligneclassement %}
                <tr><td>{{ line.position }}</td><td>{{ line.player_id.username }}</td><td>{{ line.player_id.nickname }}</td></tr>
                {% empty %}
                <p>Le classement n'est pas publié</p>
                {% endfor %}
            </table>
            {% if ligneclassement.has_other_pages %}
            <ul class="pagination">
                {% if ligneclassement.has_previous %}
                <li><a href="?page={{ ligneclassement.previous_page_number }}">&laquo;</a></li>
                {% else %}
                <li class="disabled"><span>&laquo;</span></li>
                {% endif %}
                {% for i in ligneclassement.paginator.page_range %}
                {% if ligneclassement.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% endfor %}
                {% if ligneclassement.has_next %}
                <li><a href="?page={{ ligneclassement.next_page_number }}">&raquo;</a></li>
                {% else %}
                <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
    <div style="display: flex; width: 100%; margin-top: 5px;">
        <div class="box-shadow" style="width: 100%; margin: 5px;">
            <h4>Demi-finales</h4>
        </div>
    </div>
    <div style="display: flex; width: 100%; margin-top: 5px;">
        <div class="box-shadow" style="width: 100%; margin: 5px;">
            <h4>Finale</h4>
        </div>
    </div>
{% endblock %}

spc/templates/spc/editions.html
{% extends "spc/base.html" %}
{% block content %}
    <h2>Éditions</h2>
    <div class="box-shadow">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#1" data-toggle="tab">Édition en cours <span class="badge">{{ current|length }}</span></a></li>
            <li><a href="#2" data-toggle="tab">Éditions à venir <span class="badge">{{ new|length }}</span></a></li>
            <li><a href="#3"data-toggle="tab">Éditions passées <span class="badge">{{ old|length}}</span></a></li>
        </ul>
    <div class="tab-content clearfix">
	<div class="tab-pane active" id="1">
            {% for current_edition in current %}
            <div class="edition list-group">
                <a href="/edition/{{ current_edition.id }}" class="list-group-item">Édition {{ current_edition.numero }}</a>
            </div>
            {% empty %}
            <div class="edition">
                <h4> Aucune édition n'est en cours </h4>
            </div>
            {% endfor %}
        </div>
	<div class="tab-pane" id="2">
            {% for new_edition in new %}
            <div class="edition list-group">
                <a href="/edition/{{ new_edition.id }}" class="list-group-item">Édition {{ new_edition.numero }}</a>
            </div>
            {% empty %}
            <div class="edition">
                <h4> Aucune édition n'est à venir </h4>
            </div>
            {% endfor %}
        </div>
        <div class="tab-pane" id="3">
            {% for old_edition in old %}
            <div class="edition list-group">
                <a href="/edition/{{ old_edition.id }}" class="list-group-item">Édition {{ old_edition.numero }}</a>
            </div>
            {% empty %}
            <div class="edition">
                <h4> Aucune édition n'est encore passée </h4>
            </div>
            {% endfor %}
        </div>
    </div>
    </div>
{% endblock %}

spc/templates/spc/list.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}People{% endblock %}

{% block content %}
    <h1>People</h1>
    <div id="people-list">
        {% for user in users %}
            <div class="user">
                <a href="{{ user.get_absolute_url }}">
                    {% thumbnail user.profile.photo "180x180" crop="100%" as im %}
                        <img src="{{ im.url }}">
                    {% endthumbnail %}
                </a>
                <div class="info">
                    <a href="{{ user.get_absolute_url }}" class="title">{{ user.get_full_name }}</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

spc/templates/spc/logged_out.html
{% extends "spc/base.html" %}

{% block title %}Déconnecté{% endblock %}

{% block content %}
    <h1>Déconnecté</h1>
    <p>Déconnexion effectuée avec succès. Vous pouvez <a href="{% url "login" %}">vous connecter ici</a>.</p>
{% endblock %}

spc/templates/spc/login.html
{% extends "spc/base.html" %}
{% load socialaccount %}

{% block title %}S'inscrire{% endblock %}

{% block content %}
    <h1>Log-in</h1>
    <div>
        <a class="maniaplanet_connect" href="{% provider_login_url provider.id process=process scope=scope auth_params=auth_params %}"></a>
    </div>
{% endblock %}

spc/templates/spc/password_change_done.html
{% extends "base.html" %}

{% block title %}Password changed{% endblock %}

{% block content %}
    <h1>Password changed</h1>
    <p>Your password has been successfully changed.</p>
{% endblock %}

spc/templates/spc/password_change_form.html
{% extends "base.html" %}

{% block title %}Change you password{% endblock %}

{% block content %}
    <h1>Change you password</h1>
    <p>Use the form below to change your password.</p>
    <form action="." method="post">
        {{ form.as_p }}
        <p><input type="submit" value="Change"></p>
        {% csrf_token %}
    </form>
{% endblock %}

spc/templates/spc/password_reset_complete.html
{% extends "base.html" %}

{% block title %}Password reset{% endblock %}

{% block content %}
    <h1>Password set</h1>
    <p>Your password has been set. You can <a href="{% url "login" %}">log in now</a></p>
{% endblock %}

spc/templates/spc/password_reset_confirm.html
{% extends "base.html" %}

{% block title %}Reset your password{% endblock %}

{% block content %}
    <h1>Reset your password</h1>
    {% if validlink %}
        <p>Please enter your new password twice:</p>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Change my password" /></p>
        </form>
    {% else %}
        <p>The password reset link was invalid, possibly because it has already been used. Please request a new password reset.</p>
    {% endif %}
{% endblock %}

spc/templates/spc/password_reset_done.html
{% extends "base.html" %}

{% block title %}Reset your password{% endblock %}

{% block content %}
    <h1>Reset your password</h1>
    <p>We've emailed you instructions for setting your password.</p>
    <p>If you don't receive an email, please make sure you've entered the address you registered with.</p>
{% endblock %}

spc/templates/spc/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol }}://{{ domain }}{% url "password_reset_confirm" uidb64=uid token=token %}

Your username, in case you've forgotten: {{ user.get_username }}